### ISSUE TITLE
[Security] dependencies are using an outdated lodash version with security issues

### ISSUE THREAD

**Issue by SebastiaanNijland** [privacybydesign/irmajs#12]
It would be good to updated all dependencies. It would also be good to use a tool like [dependabot](https://dependabot.com) to automate this process.

Running `npm audit`:

<img width="602" alt="Screenshot 2019-09-18 at 13 50 15" src="https://user-images.githubusercontent.com/19267753/65146050-45b56a00-da1b-11e9-9cf9-f3d94a332973.png">

Running `npm outdated`:

<img width="472" alt="Screenshot 2019-09-18 at 13 51 04" src="https://user-images.githubusercontent.com/19267753/65146114-64b3fc00-da1b-11e9-900b-8e0e2b39b4b0.png">

**Comment by confiks** [comment]
Thanks for your report. We're aware of the 'critical severity' security bugs thanks to prototype pollution in lodash; they don't affect us, as these dependencies are only used at build time. Upgrading all packages unnecessarily is in itself a security risk, as one may never known which abandoned-project-now-turned-cryptocoinstealer one might pull in as a transitive dependency.

**Comment by SebastiaanNijland** [comment]
Right, though upgrading will become more difficult the longer it is delayed. By staying up to date, the changes in these vendors can relatively easily be reviewed before actually updating.

**Comment by confiks** [comment]
That's true, although this project uses very few direct dependencies, and the ones we do use have very stables APIs. As for your second point, I don't see how we could even start to review the changes in the giant Katamari of dependencies that is the Javascript ecosystem.

**Comment by SebastiaanNijland** [comment]
I agree that for some dependencies it is not going to work, though I find that more and more of the dependencies we have in our project use SemVer quite well and scanning through the commits is quite easy for most updates.

> the giant Katamari of dependencies that is the Javascript ecosystem.

This also raises the question if upgrading doesn't actually remove the risk of pulling in those malicious packages? I somehow doubt that you can be certain you don't have one already 😄

Note that I fully agree that carelessly using dependencies is a very bad idea, but I'm not quite convinced that holding of updating as long as possible is a good idea.

**Comment by davidv1992** [comment]
We are aware that npm audit currently lists several packages used by the apps build process as vulnerable. These are for us not real issues as these packages are only used within the built toolchain and dont end up in the final code.

However, if we could it would still be nice to upgrade them. Unfortunately, the react-native ecosystem is somewhat version fragile, and offers limited support if you are not on the recommended version for the main dependencies. For this reason we are unwilling to move away from the versions specified by react-native for the version we are using. As for upgrading react native, our current dependencies, as well as several problems with the build system currently are limiting our options for upgrading that further.

We currently are looking towards options on moving away from react, which should reduce all these issues.
